version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 20.8b1
    - 21.4b0
    - 21.4b1
  - dependency-name: pip-tools
    versions:
    - 6.0.0
    - 6.0.1
    - 6.1.0
  - dependency-name: ipython
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: cryptography
    versions:
    - 3.4.1
    - 3.4.3
    - 3.4.5
    - 3.4.6
    - 3.4.7
  - dependency-name: pywebpush
    versions:
    - 1.12.0
    - 1.13.0
  - dependency-name: python-telegram-bot
    versions:
    - "13.2"
    - "13.3"
    - 13.4.1
  - dependency-name: mongoengine
    versions:
    - 0.23.0
  - dependency-name: aiohttp
    versions:
    - 3.7.4
  - dependency-name: eventlet
    versions:
    - 0.30.1
  - dependency-name: environs
    versions:
    - 9.3.0
    - 9.3.1
  - dependency-name: python-binance
    versions:
    - 0.7.9
  - dependency-name: python-socketio[client]
    versions:
    - 5.0.4
  - dependency-name: pymongo
    versions:
    - 3.11.2
  - dependency-name: dnspython
    versions:
    - 2.0.0
